import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from "@google/genai";
import { checkRateLimit, getClientIp, rateLimitResponse, RATE_LIMITS } from '@/lib/rateLimit';

export async function POST(request: NextRequest) {
    // Rate limiting
    const clientIp = getClientIp(request);
    const rateCheck = checkRateLimit(`pov-scene-img:${clientIp}`, RATE_LIMITS.imageGeneration);
    if (!rateCheck.allowed) {
        return rateLimitResponse(rateCheck);
    }

    try {
        const body = await request.json();
        const { visualNote, sceneIndex, monsterImage, productImage, povType, apiKey } = body;

        if (!visualNote) {
            return NextResponse.json(
                { error: 'Missing visual note for scene' },
                { status: 400 }
            );
        }

        // Initialize Gemini
        const genAI = new GoogleGenAI({
            apiKey: apiKey || process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY || ""
        });

        // Construct a storyboard-style prompt
        const basePrompt = `
        Create a storyboard illustration for a TikTok POV video scene.
        
        Scene ${sceneIndex !== undefined ? sceneIndex + 1 : ''}: ${visualNote}
        
        Style Requirements:
        - 3D Pixar/Disney animation style, vibrant colors
        - Cinematic composition, dynamic camera angle
        - Expressive characters with clear emotions
        - Clean, professional storyboard quality
        - 16:9 widescreen aspect ratio
        - The scene should feel like a frame from an animated short film
        
        POV Type: ${povType || 'fictional character'}
        
        IMPORTANT: This is a single scene illustration. Focus on capturing the action and emotion described above.
        Make the image vivid, colorful, and engaging - suitable for a viral TikTok video storyboard.
        `;

        // Prepare contents
        const parts: any[] = [];

        // Add character reference image for consistency
        if (monsterImage && monsterImage.startsWith('data:')) {
            parts.push({
                inlineData: {
                    mimeType: monsterImage.startsWith('data:image/jpeg') ? 'image/jpeg' : 'image/png',
                    data: monsterImage.includes('base64,') ? monsterImage.split('base64,')[1] : monsterImage
                }
            });
            parts.push({ text: "Use this character as the main character in the scene. Keep the character's appearance consistent." });
        }

        // Add product image for context
        if (productImage && productImage.startsWith('data:')) {
            parts.push({
                inlineData: {
                    mimeType: productImage.startsWith('data:image/jpeg') ? 'image/jpeg' : 'image/png',
                    data: productImage.includes('base64,') ? productImage.split('base64,')[1] : productImage
                }
            });
            parts.push({ text: "Include this product in the scene where appropriate." });
        }

        // Add the main prompt
        parts.push({ text: basePrompt });

        const contents: any[] = [{
            role: 'user',
            parts: parts
        }];

        // Try primary model
        try {
            const imageResponse = await genAI.models.generateContent({
                model: 'gemini-3-pro-image-preview',
                contents: contents,
                config: {
                    responseModalities: ['image'],
                }
            });

            const candidates = imageResponse.candidates;
            const responseParts = candidates?.[0]?.content?.parts;
            const imagePart = responseParts?.find((p: any) => p.inlineData);

            if (imagePart && imagePart.inlineData) {
                const base64 = imagePart.inlineData.data;
                const mimeType = imagePart.inlineData.mimeType || 'image/png';
                return NextResponse.json({ result: `data:${mimeType};base64,${base64}` });
            }

            throw new Error("No image generated by primary model");

        } catch (primaryError) {
            console.warn("Primary model failed for scene image, using Pollinations fallback:", primaryError);

            // Fallback: Pollinations.ai
            const safePrompt = encodeURIComponent(
                `Storyboard illustration, Pixar 3D style, cinematic, vibrant: ${visualNote}`.slice(0, 400)
            );
            const seed = Math.floor(Math.random() * 100000);
            const imageUrl = `https://image.pollinations.ai/prompt/${safePrompt}?width=1280&height=720&model=flux&seed=${seed}&nologo=true`;

            return NextResponse.json({ result: imageUrl });
        }

    } catch (error) {
        console.error('Scene Image Generation API Error:', error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Unknown error' },
            { status: 500 }
        );
    }
}
