'use client';

import { useKolMiniLuluStore } from "@/stores/useKolMiniLuluStore";
import { useRouter } from "next/navigation";
import { cn } from "@/lib/utils";
import { ArrowRight, Sparkles, Download, Loader2, RefreshCw } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import { toast } from "sonner";
import { useTranslations, useLocale } from "next-intl";
import { m, AnimatePresence } from "framer-motion";

export default function Step2CastingPage() {
    const t = useTranslations('KolMiniLulu.Step2');
    const locale = useLocale();
    const router = useRouter();
    const {
        selectedCharacter,
        setCharacter,
        customPrompt,
        miniConfig,
        luluConfig,
        setMiniConfig,
        setLuluConfig,
    } = useKolMiniLuluStore();

    const [generatingState, setGeneratingState] = useState<{ mini: boolean; lulu: boolean }>({ mini: false, lulu: false });
    const hasAutoGenerated = useRef(false);

    const handleGenerate = async (charId: 'mini' | 'lulu') => {
        setGeneratingState(prev => ({ ...prev, [charId]: true }));

        try {
            const res = await fetch('/api/kol-mini-lulu/generate-character', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    character: charId,
                    idea: customPrompt,
                    prompt: '', // Empty = auto-design from story idea
                    useReferenceImage: true, // Signal API to use mascot reference
                })
            });

            const data = await res.json();
            if (!res.ok) throw new Error(data.error || 'Failed');

            if (data.imageUrl) {
                if (charId === 'mini') setMiniConfig({ image: data.imageUrl });
                else setLuluConfig({ image: data.imageUrl });
                toast.success(`✨ ${charId === 'mini' ? 'Mini' : 'Lulu'} đã sẵn sàng!`);
            }
        } catch (error) {
            console.error(error);
            toast.error('Không thể tạo ảnh, thử lại nhé!');
        } finally {
            setGeneratingState(prev => ({ ...prev, [charId]: false }));
        }
    };

    // Auto-generate on mount if no images yet
    useEffect(() => {
        if (hasAutoGenerated.current) return;
        hasAutoGenerated.current = true;

        const chars: Array<'mini' | 'lulu'> = [];
        if (selectedCharacter === 'mini' || selectedCharacter === 'both') {
            if (!miniConfig.image) chars.push('mini');
        }
        if (selectedCharacter === 'lulu' || selectedCharacter === 'both') {
            if (!luluConfig.image) chars.push('lulu');
        }

        // Stagger generation
        chars.forEach((char, i) => {
            setTimeout(() => handleGenerate(char), i * 500);
        });
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    const handleNext = () => {
        if (selectedCharacter) {
            router.push(`/${locale}/kol-mini-lulu/step-3-script`);
        }
    };

    const renderCard = (type: 'mini' | 'lulu') => {
        const isMini = type === 'mini';
        const config = isMini ? miniConfig : luluConfig;
        const isLoading = generatingState[type];
        const hasImage = !!config?.image;

        return (
            <m.div
                key={type}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: isMini ? 0 : 0.15 }}
                className="relative group flex flex-col bg-[#0f1115] rounded-2xl overflow-hidden border border-white/5 hover:border-orange-500/20 transition-all shadow-2xl"
            >
                {/* Image Preview */}
                <div className="aspect-[3/4] relative w-full bg-[#1a1d24] overflow-hidden">
                    <AnimatePresence mode="wait">
                        {isLoading ? (
                            <m.div
                                key="loading"
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                exit={{ opacity: 0 }}
                                className="absolute inset-0 flex flex-col items-center justify-center gap-3 bg-[#0d0f13]"
                            >
                                {/* Animated rings */}
                                <div className="relative w-20 h-20 flex items-center justify-center">
                                    <div className="absolute inset-0 rounded-full border-2 border-orange-500/20 animate-ping" />
                                    <div className="absolute inset-2 rounded-full border-2 border-pink-500/30 animate-ping" style={{ animationDelay: '0.3s' }} />
                                    <Sparkles className="w-8 h-8 text-orange-400 animate-pulse" />
                                </div>
                                <div className="text-center">
                                    <p className="text-xs font-semibold text-white">Đang thiết kế trang phục...</p>
                                    <p className="text-[10px] text-gray-500 mt-1">AI đang tạo hình {isMini ? 'Mini 🐱' : 'Lulu 🐶'}</p>
                                </div>
                            </m.div>
                        ) : hasImage ? (
                            <m.img
                                key="image"
                                initial={{ opacity: 0, scale: 1.05 }}
                                animate={{ opacity: 1, scale: 1 }}
                                exit={{ opacity: 0 }}
                                transition={{ duration: 0.5 }}
                                src={config.image!}
                                alt={type}
                                className="w-full h-full object-cover"
                            />
                        ) : (
                            <m.div
                                key="empty"
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="absolute inset-0 flex flex-col items-center justify-center gap-2 text-gray-600"
                            >
                                <Sparkles className="w-8 h-8 opacity-30" />
                                <p className="text-xs">Chưa có ảnh</p>
                            </m.div>
                        )}
                    </AnimatePresence>

                    {/* Gradient Overlay */}
                    {hasImage && !isLoading && (
                        <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent" />
                    )}

                    {/* Character Name */}
                    {!isLoading && (
                        <div className="absolute bottom-3 left-3 z-20">
                            <h3 className="text-base font-bold text-white flex items-center gap-1.5">
                                {isMini ? 'Mini' : 'Lulu'}
                                <span>{isMini ? '🐱' : '🐶'}</span>
                            </h3>
                        </div>
                    )}
                </div>

                {/* Action Bar */}
                <div className="p-3 flex items-center gap-2 bg-[#0d0f13] border-t border-white/5">
                    {/* Regenerate Button */}
                    <button
                        onClick={() => handleGenerate(type)}
                        disabled={isLoading}
                        className="flex-1 flex items-center justify-center gap-2 py-2 px-3 bg-gradient-to-r from-orange-500 to-pink-500 hover:from-orange-400 hover:to-pink-400 rounded-lg text-white text-xs font-semibold transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-orange-500/20"
                    >
                        {isLoading ? (
                            <>
                                <Loader2 className="w-3.5 h-3.5 animate-spin" />
                                <span>Đang tạo...</span>
                            </>
                        ) : (
                            <>
                                <RefreshCw className="w-3.5 h-3.5" />
                                <span>Tạo lại</span>
                            </>
                        )}
                    </button>

                    {/* Download Button */}
                    {hasImage && !isLoading && (
                        <a
                            href={config.image!}
                            download={`${type}-outfit.png`}
                            className="p-2 bg-white/5 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white transition-all border border-white/5"
                            title="Tải ảnh"
                        >
                            <Download className="w-4 h-4" />
                        </a>
                    )}
                </div>
            </m.div>
        );
    };

    return (
        <div className="max-w-4xl mx-auto pb-12 pt-2 md:pt-4">
            {/* Header */}
            <div className="flex items-center justify-between mb-6 px-1">
                <div>
                    <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-orange-400 to-pink-500">
                        {t('title')}
                    </h1>
                    <p className="text-gray-500 text-xs mt-0.5">
                        {t('subtitle')}
                    </p>
                </div>

                {/* Character Selector */}
                <div className="flex gap-1 p-1 bg-[#1a1d24] rounded-lg border border-white/5">
                    {(['mini', 'lulu', 'both'] as const).map((id) => (
                        <button
                            key={id}
                            onClick={() => setCharacter(id)}
                            className={cn(
                                "px-3 py-1.5 rounded-md text-xs font-semibold transition-all",
                                selectedCharacter === id
                                    ? "bg-gradient-to-r from-orange-500 to-pink-500 text-white shadow-sm"
                                    : "text-gray-400 hover:text-white hover:bg-white/5"
                            )}
                        >
                            {id === 'mini' && t('mini')}
                            {id === 'lulu' && t('lulu')}
                            {id === 'both' && t('both')}
                        </button>
                    ))}
                </div>
            </div>

            {/* Story Context Badge */}
            {customPrompt && (
                <div className="mb-5 px-1">
                    <div className="inline-flex items-center gap-2 px-3 py-1.5 bg-purple-500/10 border border-purple-500/20 rounded-full">
                        <Sparkles className="w-3 h-3 text-purple-400" />
                        <span className="text-[11px] text-purple-300 font-medium">Cốt truyện: </span>
                        <span className="text-[11px] text-gray-400 truncate max-w-[300px]">{customPrompt}</span>
                    </div>
                </div>
            )}

            {/* Cards Grid */}
            <div className="flex justify-center">
                <div className={cn(
                    "grid gap-5 w-full transition-all duration-500",
                    selectedCharacter === 'both'
                        ? "grid-cols-1 sm:grid-cols-2 max-w-2xl"
                        : "grid-cols-1 max-w-xs"
                )}>
                    {(selectedCharacter === 'mini' || selectedCharacter === 'both') && renderCard('mini')}
                    {(selectedCharacter === 'lulu' || selectedCharacter === 'both') && renderCard('lulu')}
                </div>
            </div>

            {/* Continue Button */}
            <div className="flex justify-end pt-8 mt-4 border-t border-white/5">
                <button
                    onClick={handleNext}
                    disabled={!selectedCharacter}
                    className="flex items-center gap-2 px-6 py-2.5 bg-white text-black hover:bg-gray-100 rounded-full text-sm font-bold shadow-lg disabled:opacity-40 disabled:cursor-not-allowed transition-all hover:-translate-y-0.5"
                >
                    {t('btn_continue')}
                    <ArrowRight className="w-4 h-4" />
                </button>
            </div>
        </div>
    );
}
