import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenAI } from "@google/genai";
import { checkRateLimit, getClientIp, rateLimitResponse, RATE_LIMITS } from '@/lib/rateLimit';
import { POVType } from '@/types/pov-studio';

export async function POST(request: NextRequest) {
    // Rate limiting
    const clientIp = getClientIp(request);
    const rateCheck = checkRateLimit(`pov-studio-image:${clientIp}`, RATE_LIMITS.imageGeneration);
    if (!rateCheck.allowed) {
        return rateLimitResponse(rateCheck);
    }

    try {
        const body = await request.json();
        const { monsterDescription, povType, productImage, apiKey } = body;

        if (!monsterDescription) {
            return NextResponse.json(
                { error: 'Missing monster description' },
                { status: 400 }
            );
        }

        // Initialize Gemini
        const genAI = new GoogleGenAI({
            apiKey: apiKey || process.env.GEMINI_API_KEY || process.env.NEXT_PUBLIC_GEMINI_API_KEY || ""
        });

        const getPovLabel = (type: POVType) => {
            switch (type) {
                case 'bacteria': return 'Bacteria or Micro-organism';
                case 'monster': return 'Fantasy Monster';
                case 'object': return 'Inanimate Object (living)';
                case 'pet': return 'Cute Pet Animal';
                case 'villain': return 'Comical Villain';
                default: return 'Fictional Character';
            }
        };

        // Construct a highly detailed prompt for 3D Pixar style
        let basePrompt = `
        Create a 3D Pixar/Disney-style animation character portrait. High quality, vibrant colors, expressive lighting.
        
        Character Type constraint: ${getPovLabel(povType as POVType)}.
        Character Details: ${monsterDescription}.
        `;

        // Add Product Logic
        if (productImage) {
            basePrompt += `
        IMPORTANT CONTEXT: 
        The character must be interacting with or inspired by the provided product image.
        If the product is clothing, the character should wear it.
        If it's an object/food/cosmetic, the character should hold it or stand next to it admiringly. 
        Match the color scheme and vibe of the product.
        `;
        }

        basePrompt += `
        Style: 3D render, Pixar animation quality, Octane render, 8K, highly detailed, cinematic lighting.
        Aspect Ratio: 1:1 (Square).
        Background: Studio photography style, clean studio background with soft lighting, matching character vibe.
        Focus: The character should be the central focus, facing the camera.
        `;

        // Prepare contents
        const parts: any[] = [];

        // Add Product Image Context
        if (productImage) {
            parts.push({
                inlineData: {
                    mimeType: productImage.startsWith('data:image/jpeg') ? 'image/jpeg' : 'image/png',
                    data: productImage.includes('base64,') ? productImage.split('base64,')[1] : productImage
                }
            });
        }

        // Add Text Prompt
        parts.push({ text: basePrompt });

        const contents: any[] = [{
            role: 'user',
            parts: parts
        }];

        // Try primary model: gemini-3-pro-image-preview
        try {
            const imageResponse = await genAI.models.generateContent({
                model: 'gemini-3-pro-image-preview',
                contents: contents,
                config: {
                    responseModalities: ['image'],
                }
            });

            const candidates = imageResponse.candidates;
            const parts = candidates?.[0]?.content?.parts;
            const imagePart = parts?.find((p: any) => p.inlineData);

            if (imagePart && imagePart.inlineData) {
                const base64 = imagePart.inlineData.data;
                const mimeType = imagePart.inlineData.mimeType || 'image/png';
                return NextResponse.json({ result: `data:${mimeType};base64,${base64}` });
            }

            throw new Error("No image generated by primary model");

        } catch (primaryError) {
            console.warn("gemini-3-pro-image-preview failed for POV Image, using Pollinations fallback:", primaryError);

            // Fallback: Pollinations.ai (Text only, ignores image input)
            const safePrompt = encodeURIComponent(basePrompt.slice(0, 300));
            const seed = Math.floor(Math.random() * 100000);
            const imageUrl = `https://image.pollinations.ai/prompt/${safePrompt}?width=1024&height=1024&model=flux&seed=${seed}&nologo=true`;

            return NextResponse.json({ result: imageUrl });
        }

    } catch (error) {
        console.error('POV Image Generation API Error:', error);
        return NextResponse.json(
            { error: error instanceof Error ? error.message : 'Unknown error' },
            { status: 500 }
        );
    }
}
